# Generated by Django 3.1.3 on 2020-11-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id_bicicleta', models.IntegerField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('candado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Portico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_portico', models.IntegerField()),
                ('ubicacion', models.TextField()),
                ('id_bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.bicicleta')),
            ],
        ),
    ]
